name: Running Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/hello-world-composite-action@v1

      - name: Install
        uses: ./.github/actions/install

      - name: Run the tests
        run: yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  snapshot:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/hello-world-composite-action@v1

      - name: Install
        uses: ./.github/actions/install

      - name: Build screenshots
        run: yarn build
        env:
          CCN_ENDPOINT: ${{ secrets.CCN_ENDPOINT }}
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}

      - name: Upload snapshots to Percy
        run: yarn test:snapshot
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
