name: Running Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 

    - name: Set up Node.js
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: yarn install --production=false

    - name: Run the tests
      run: yarn test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build screenshots
      run: yarn build

    - name: Upload snapshots to Percy
      run: yarn test:snapshot
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
